[platformio]
default_envs = esp32-c3-devkitm-1

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.3
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
lib_deps =
  ${env.lib_deps}
  adafruit/Adafruit NeoPixel @ ^1.12.5
build_flags =
  ${env.build_flags}
  -D GOLDENJOY_STATUS_LED_RGB=1

[env:esp32-c3-supermini]
board = esp32-c3-devkitm-1
build_flags =
  ${env.build_flags}
  -D GOLDENJOY_STATUS_LED_RGB=0
  -D GOLDENJOY_STATUS_LED_ACTIVE_LOW=1
